### ISSUE TITLE
Implement full text search

### ISSUE THREAD

**Issue by batpad** [mapbox/osm-comments-api#12]
We need to be able to search by note comment, changeset comment, and content of changeset discussions. 

See: http://www.postgresql.org/docs/current/static/textsearch-intro.html . We probably want to implement tsvector indexes and use Tsearch2 for search.

 - [ ] Create indexes appropriate to full text searching
 - [ ] Test performance
 - [ ] Integrate full text search query params into API

**Comment by batpad** [comment]
Related to https://github.com/mapbox/osm-comments-parser/issues/2

**Comment by batpad** [comment]
Currently creating the fulltext indexes with something like: `CREATE INDEX changeset_tags_value_tsvector_idex ON changeset_tags USING gin(to_tsvector('english', value));`

@geohacker does this look okay to you? This will probably be better for searching english than other languages. I think that's okay, at least for now?

**Comment by geohacker** [comment]
This looks like what I'd do. :+1:
