### ISSUE TITLE
Define API / Scope

### ISSUE THREAD

**Issue by batpad** [mapbox/osm-comments-api#2]
Write out API scope / definition to serve as a starting point.

This will emerge / be related to the user stories. My preference for an initial version is to keep the API completely read-only. I.e. not have a concept of user management, etc. - just simply a query tool allowing for fairly complex queries of notes and changeset comments.

Will create a wiki page with an API definition once some user stories are in.

/cc @rclark @mikelmaron

**Comment by rclark** [comment]
:+1: to read-only access to the datastore that you're putting together in postgres. I see no need for anything more than that.

**Comment by batpad** [comment]
Started an API docs page. Will add to it as functionality is added: https://github.com/mapbox/osm-comments-api/wiki/API-Documentation
