### ISSUE TITLE
Quick structural suggestions

### ISSUE THREAD

**Issue by rclark** [mapbox/osm-comments-api#3]
Hey @batpad -- just a couple of structural suggestions:

- consider a simple module-based approach to your data access layer instead of a strict class-oriented model approach. Example:

    ```js
    var config = require('./lib/config')();
    var notes = {};
    module.exports = notes;

    notes.get = function(id, callback) { ... };
    notes.search = function(params, callback) { ... };
    ```

- because they have really well-defined inputs, these module functions should be simple to unit test

- try to make the logic in your middleware functions absolutely trivial. The middleware's job should be to 
  - parse request inputs into arguments to hand off to business functions like those above
  - convert the results of business functions into HTTP responses (and errors)

This leaves you in a place where the majority of the logic you need to write tests for is very simple to unit test. Then tests that access the API via HTTP need only really assert that inputs are parsed properly, and outputs interpreted correctly.

**Comment by batpad** [comment]
@rclark thanks for this. Refactored here: https://github.com/mapbox/osm-comments-api/commit/da2ab1519f650ad52b48e36ad7070abf91ec18b0

Please let me know if this can be improved.

**Comment by batpad** [comment]
@rclark could you look over the commit referenced above and let me know if there are further suggestions or if this can be closed? Thanks.

**Comment by batpad** [comment]
Closing this - opening separate tickets for refactoring / getting code closer to general mapbox coding styles / standards.
