### ISSUE TITLE
Show count of changesets queried when from date input is given

### ISSUE THREAD

**Issue by manoharuss** [mapbox/osm-comments-api#46]
Per voice on validation scrum @batpad would be great to have a **count** of changesets and notes returned by [osm-comments](https://www.mapbox.com/osm-comments/) when a from date parameter is given.

Ideally that count - our number of comments=comments of other users in all of OSM from a query like this https://www.mapbox.com/osm-comments/#/changesets/?q=users%3A%2A with a from date.

cc @krishnanammala @batpad @geohacker

**Comment by geohacker** [comment]
Ah yes I thought about this when patching the notes stuff earlier this week. Good one.

**Comment by batpad** [comment]
@manoharuss this should be all fine now with the `Total` display, and the ability to search from a particular date with `from:YYYY-MM-DD`? Closing, please re-open if there's something I missed.
