### ISSUE TITLE
Handle errors

### ISSUE THREAD

**Issue by batpad** [mapbox/osm-comments-api#5]
Right now, there is no good error handling where user specifies invalid query parameters, etc.

We need to be able to bubble up errors and return correct HTTP status code and error message based on type of error.

**Comment by rclark** [comment]
@batpad see https://github.com/mapbox/mapbox-core/issues/35 for some error handling discussion in the context of our larger APIs. This would be a good place to start trying out the pattern outlined in that discussion.

**Comment by batpad** [comment]
@rclark this approach looks great! Shall study code, and play around with writing an error handling middleware and defining error types. Shall ping back if I run into any road-blocks.

**Comment by batpad** [comment]
Errors are being handled with appropriate HTTP status codes being returned:

 - 400 Bad Request for when user supplies invalid query parameters
 - 404 Not Found for when user attempts to fetch a resource that does not exist.
