### ISSUE TITLE
API for Stats

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-comments-api#56]
We now parse OSM change files to gather [stats for a set of users](https://github.com/mapbox/osm-comments-parser/pull/28) - let's add API methods for this.

cc @batpad @Rub21 @ajithranka 

I think for a start:

1. from - timestamp
2. to -timestamp
3. users - comma separated list of users.

**Comment by batpad** [comment]
@geohacker can you outline what all the API would return in terms of stats? This is like total number of nodes added, edited, created - ways added, edited, created - list of tags added, edited, deleted? All this per user?

**Comment by geohacker** [comment]
@batpad something like:

```
{
 'from': timestamp,
 'to': timestamp,
 'totals': {},
 [
   {
     'user_id': 1234,
     'username': 'geohacker',
     'count_changesets': 4,
     'nodes_added': 10,
    .....
   }
 ]
}
```

**Comment by Rub21** [comment]
@geohacker : Would be good add:
```
nodes :{
    modify: 12
    delete:34
    create: 12
}
ways :{
    modify: 32
    delete:34
    create: 12
}
...

```
As we find in the replication file. Also the same thing for  counting the tags.

**Comment by geohacker** [comment]
@Rub21 - oh right, yes - I'll make the JSON response that way.
