### ISSUE TITLE
Get /stats within a bbox

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-comments-api#62]
We should be able to expand the /stats end point to filter by changes in a bbox.

**Comment by geohacker** [comment]
cc @batpad

**Comment by batpad** [comment]
You have changeset references in the stats table? Then filter by the bbox of the changesets should be easy.

**Comment by geohacker** [comment]
What if we do:

``
select id from stats where changesets <@ (select array_agg(id) from changesets WHERE ST_Intersects(bbox, ST_MakeEnvelope(-119.49983896598195, 33.48167607676609, -116.79165467448189, 34.87839127285146, 4326)) AND closed_at > '2017-02-14T12:50:39.338Z');
``
