### ISSUE TITLE
Changeset discrepancy 

### ISSUE THREAD

**Issue by kepta** [mapbox/osm-comments-api#82]
On querying the server with the following params https://osm-comments-api.mapbox.com/api/v1/stats?from=2017-03-13T00:00:00.000Z&to=2017-03-13T22:59:59.000Z

We get an interesting result,
It returns a [changeset:39292039](https://osmcha.mapbox.com/39292039/) which was created back in 2016.

cc @geohacker

**Comment by kepta** [comment]
As per conversation with @geohacker we have identified the code that might be creating this problem.
https://github.com/mapbox/osm-comments-parser/blob/master/changes/counter.js#L22

**Comment by geohacker** [comment]
@kepta thank you for identifying this bug. This clearly exposes a major problem in the parser. could we perhaps move this ticket to the parser repo?

**Comment by kepta** [comment]
@geohacker sure I will close this and open it there.

**Comment by kepta** [comment]
https://github.com/mapbox/osm-comments-parser/issues/32
